### ISSUE TITLE
exporter crashes when unable to parse lines

### ISSUE THREAD

**Issue by bmm-alc** [sergeymakinen/postfix_exporter#19]
I've luanched the exporter this way to test it `./postfix_exporter --collector=journald`
postfix version: `3.6.4-1ubuntu1.3`

```
time=2024-12-31T09:39:58.031Z level=INFO source=main.go:40 msg="Starting postfix_exporter" version="(version=2.0.2, branch=HEAD, revision=7df2ad63c11a8b923918bdf21bf545a8e25eb26b)"
time=2024-12-31T09:39:58.031Z level=INFO source=main.go:41 msg="Build context" context="(go=go1.23.4, platform=linux/amd64, user=root@50293ece55ce, date=20241218-23:54:59, tags=netgo)"
time=2024-12-31T09:39:58.036Z level=INFO source=tls_config.go:347 msg="Listening on" address=[::]:9907
time=2024-12-31T09:39:58.036Z level=INFO source=tls_config.go:350 msg="TLS is disabled." http2=false address=[::]:9907
time=2024-12-31T09:45:13.819Z level=WARN source=exporter.go:195 msg="Error parsing host reply" record="Dec 31 09:45:13 email1 postfix/smtp[2772652]: 1FEDF46DB7: to=<s9d6y7d0p7d0u8i7@imperatorz.slack.com>, relay=inbound-smtp.us-east-1.amazonaws.com[54.197.5.236]:25, delay=1.2, delays=0.08/0.02/0.67/0.45, dsn=2.0.0, status=sent (250 OK d3gsb37958a0njtf9phnplbs2nq5pjousooa5701)" err="failed to find host reply in \"250 OK d3gsb37958a0njtf9phnplbs2nq5pjousooa5701\""
time=2024-12-31T09:48:13.568Z level=WARN source=exporter.go:195 msg="Error parsing host reply" record="Dec 31 09:48:13 email1 postfix/smtp[2772677]: F197C46DFD: to=<m4s3t9x1a6m4w6s3@imperatorz.slack.com>, relay=inbound-smtp.us-east-1.amazonaws.com[3.211.210.226]:25, delay=1.2, delays=0.09/0.03/0.67/0.44, dsn=2.0.0, status=sent (250 OK 72c7lsnf5n4abk6qb6etkepehlmc8ls16pcsnt81)" err="failed to find host reply in \"250 OK 72c7lsnf5n4abk6qb6etkepehlmc8ls16pcsnt81\""
time=2024-12-31T09:48:13.569Z level=WARN source=exporter.go:195 msg="Error parsing host reply" record="Dec 31 09:48:13 email1 postfix/smtp[2772676]: ECD0146DB7: to=<m4s3t9x1a6m4w6s3@imperatorz.slack.com>, relay=inbound-smtp.us-east-1.amazonaws.com[44.210.166.32]:25, delay=1.2, delays=0.07/0.02/0.72/0.43, dsn=2.0.0, status=sent (250 OK lqeate295ekv4nfppl5qvtn1du72ddb3qjekus81)" err="failed to find host reply in \"250 OK lqeate295ekv4nfppl5qvtn1du72ddb3qjekus81\""
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x95b069]

goroutine 16 [running]:
github.com/sergeymakinen/postfix_exporter/v2/exporter.(*Exporter).scrape.func1({0xc00029bb80, 0x4, 0x4})
        /__w/postfix_exporter/postfix_exporter/exporter/exporter.go:171 +0x249
github.com/sergeymakinen/postfix_exporter/v2/exporter.(*Exporter).scrape(0xc0000a5d40, {{0x0, 0xffffffffffff3875, 0x0}, {0xc000174c70, 0x6}, {0xc000174c77, 0x7}, {0xc000174c7f, 0x4}, ...}, ...)
        /__w/postfix_exporter/postfix_exporter/exporter/exporter.go:294 +0x1691
github.com/sergeymakinen/postfix_exporter/v2/exporter.(*journaldCollector).Write(0xc000012d50, {0xc0001a2000?, 0x108, 0x0?})
        /__w/postfix_exporter/postfix_exporter/exporter/journald.go:53 +0xb5
github.com/coreos/go-systemd/v22/sdjournal.(*JournalReader).Follow(0xc000012d20, 0xc000032540, {0xb68980, 0xc000012d50})
        /github/home/go/pkg/mod/github.com/coreos/go-systemd/v22@v22.5.0/sdjournal/read.go:221 +0x18d
created by github.com/sergeymakinen/postfix_exporter/v2/exporter.collectFromJournald in goroutine 1
        /__w/postfix_exporter/postfix_exporter/exporter/journald.go:42 +0x267
```

**Comment by sergeymakinen** [comment]
Thanks for the report!
Tried to launch tests with those lines from the log and didn't find any suspicious things, it sounds like an offending line is somewhere after `Dec 31 09:48:13 email1 postfix/smtp[2772676]: ECD0146DB7...`, do you have any possibility to share a bit of logs after that line?
I just tried to have a brief look at code around `exporter.go:171` and not sure what caused this by far but it should be definitely fixed.

**Comment by bmm-alc** [comment]
is that what you want ?
```
Dec 31 09:48:13 email1 postfix/smtp[2772676]: ECD0146DB7: to=<m4s3t9x1a6m4w6s3@imperatorz.slack.com>, relay=inbound-smtp.us-east-1.amazonaws.com[44.210.166.32]:25, delay=1.2, delays=0.07/0.02/0.72/0.43, dsn=2.0.0, status=sent (250 OK lqeate295ekv4nfppl5qvtn1du72ddb3qjekus81)
Dec 31 09:48:13 email1 postfix/qmgr[2501036]: ECD0146DB7: removed
Dec 31 09:48:36 email1 postfix/smtpd[2772670]: connect from server[xxx.xxx.xxx.xx]
Dec 31 09:48:36 email1 postfix/smtpd[2772670]: A773746DB7: client=server[xxx.xxx.xxx.xx]
Dec 31 09:48:36 email1 postfix/cleanup[2772674]: A773746DB7: message-id=<20241231094836.A1B1E13B20E@dev6.localdomain>
```

**Comment by sergeymakinen** [comment]
Yeah, thanks, although it's not related to these logs (thank you anyway!), I think I got it and will post a fix shortly.
